name: Cypress Tests

on: 
  push:
    branches: master

  pull_request:
    branches: master

  workflow_dispatch:
    inputs:
      BROWSER1:
        description: Browser for run 1
        required: true
        default: firefox
        type: choice
        options:
        - chrome
        - edge
        - electron
        - firefox
      BROWSER2:
        description: Browser for run 2
        required: true
        default: chrome
        type: choice
        options:
        - chrome
        - edge
        - electron
        - firefox

env:
  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

jobs:
  
  Browser-1-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: ${{inputs.BROWSER1}}
          start: npx cypress run
          group: ${{inputs.BROWSER1}} test group

  Browser-2-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: ${{inputs.BROWSER2}}
          start: npx cypress run
          group: ${{inputs.BROWSER2}} test group