name: Cypress Tests

on: [push,pull_request]

env:
  CYPRESS_RECORD_KEY: 3d088a7d-910a-4e51-a06d-4f6e300c3d65

jobs:
  
  firefox-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          start: npx cypress run --browser firefox
          group: Firefox test group

  chrome-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          start: npx cypress run --browser chrome
          group: Chrome test group