name: Cypress Tests

on: 
  pull_request:
    branches: master

  workflow_dispatch:
    inputs:
      TEST:
        description: Select the test to run
        required: true
        default: Successful Sign In
        type: choice
        options:
        - Successful Sign In
        - Add Items to Cart and Remove Them from the Products Page
        - Add Items to Cart and Remove Them from the Checkout Page
        - Add Items to Cart and Remove Them from the Product Details Page
        - Buy Items
        - Add Items to Cart, Logout, and Login Again to Verify Cart Persistance
        - Verify All Sorting Options on Products Page
      
      BROWSER1:
        description: Browser for run 1
        required: true
        default: firefox
        type: choice
        options:
        - chrome
        - edge
        - electron
        - firefox
      
      BROWSER2:
        description: Browser for run 2
        required: true
        default: chrome
        type: choice
        options:
        - chrome
        - edge
        - electron
        - firefox

env:
  CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}

jobs:
  
  Browser-1-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: ${{inputs.BROWSER1}}
          start: npm run ${{inputs.TEST}}
          group: Browser 1 test group

  Browser-2-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: ${{inputs.BROWSER2}}
          start: npm run ${{inputs.TEST}}
          group: Browser 2 test group